#!/bin/bash

if [ ! -f "${HOME}/Desktop/subtitleedit.desktop" ]; then
  cp /usr/share/applications/subtitleedit.desktop "${HOME}/Desktop/"
fi

touch "${HOME}/.config/panel-reload"
gio mime inode/directory caja-browser.desktop
gio mime application/x-terminal-emulator foot.desktop

exec /usr/local/bin/subtitleedit

